/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"

#import "Core.h"

@interface CTokenAccess_t : NSObject <NSCoding> {
  Customer_t * __customer;
  NSString * __token;

  BOOL __customer_isset;
  BOOL __token_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=customer, setter=setCustomer:) Customer_t * customer;
@property (nonatomic, retain, getter=token, setter=setToken:) NSString * token;
#endif

- (id) init;
- (id) initWithCustomer: (Customer_t *) customer token: (NSString *) token;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (Customer_t *) customer;
- (void) setCustomer: (Customer_t *) customer;
#endif
- (BOOL) customerIsSet;

#if !__has_feature(objc_arc)
- (NSString *) token;
- (void) setToken: (NSString *) token;
#endif
- (BOOL) tokenIsSet;

@end

@protocol CustomerService_t <NSObject>
- (CTokenAccess_t *) createAccount: (Customer_t *) customer password: (NSString *) password;  // throws ServiceException_t *, TException
- (CTokenAccess_t *) authenticate: (NSString *) email password: (NSString *) password;  // throws ServiceException_t *, TException
- (CTokenAccess_t *) newToken;  // throws ServiceException_t *, TException
- (void) addSocialAccount: (NSString *) email socialAccount: (SocialAccount_t *) socialAccount;  // throws ServiceException_t *, TException
@end

@interface CustomerService_tClient : NSObject <CustomerService_t> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface CustomerService_tProcessor : NSObject <TProcessor> {
  id <CustomerService_t> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithCustomerService_t: (id <CustomerService_t>) service;
- (id<CustomerService_t>) service;
@end

@interface CustomerServiceConstants : NSObject {
}
+ (NSString *) CTOKEN_NAME;
@end
