/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.talool.api.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum AcquireStatus_t implements org.apache.thrift.TEnum {
  PURCHASED(0),
  REDEEMED(1),
  REJECTED_CUSTOMER_SHARE(2),
  REJECTED_MERCHANT_SHARE(3),
  ACCEPTED_MERCHANT_SHARE(4),
  ACCEPTED_CUSTOMER_SHARE(5),
  PENDING_ACCEPT_MERCHANT_SHARE(6),
  PENDING_ACCEPT_CUSTOMER_SHARE(7);

  private final int value;

  private AcquireStatus_t(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AcquireStatus_t findByValue(int value) { 
    switch (value) {
      case 0:
        return PURCHASED;
      case 1:
        return REDEEMED;
      case 2:
        return REJECTED_CUSTOMER_SHARE;
      case 3:
        return REJECTED_MERCHANT_SHARE;
      case 4:
        return ACCEPTED_MERCHANT_SHARE;
      case 5:
        return ACCEPTED_CUSTOMER_SHARE;
      case 6:
        return PENDING_ACCEPT_MERCHANT_SHARE;
      case 7:
        return PENDING_ACCEPT_CUSTOMER_SHARE;
      default:
        return null;
    }
  }
}
