/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.talool.api.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DealAcquire_t implements org.apache.thrift.TBase<DealAcquire_t, DealAcquire_t._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DealAcquire_t");

  private static final org.apache.thrift.protocol.TField DEAL_ACQUIRE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("dealAcquireId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DEAL_FIELD_DESC = new org.apache.thrift.protocol.TField("deal", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField SHARED_BY_MERCHANT_FIELD_DESC = new org.apache.thrift.protocol.TField("sharedByMerchant", org.apache.thrift.protocol.TType.STRUCT, (short)4);
  private static final org.apache.thrift.protocol.TField SHARED_BY_CUSTOMER_FIELD_DESC = new org.apache.thrift.protocol.TField("sharedByCustomer", org.apache.thrift.protocol.TType.STRUCT, (short)5);
  private static final org.apache.thrift.protocol.TField SHARE_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("shareCount", org.apache.thrift.protocol.TType.I32, (short)6);
  private static final org.apache.thrift.protocol.TField REDEEMED_FIELD_DESC = new org.apache.thrift.protocol.TField("redeemed", org.apache.thrift.protocol.TType.I64, (short)7);
  private static final org.apache.thrift.protocol.TField CREATED_FIELD_DESC = new org.apache.thrift.protocol.TField("created", org.apache.thrift.protocol.TType.I64, (short)8);
  private static final org.apache.thrift.protocol.TField UPDATED_FIELD_DESC = new org.apache.thrift.protocol.TField("updated", org.apache.thrift.protocol.TType.I64, (short)9);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DealAcquire_tStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DealAcquire_tTupleSchemeFactory());
  }

  public String dealAcquireId; // optional
  public Deal_t deal; // required
  public String status; // optional
  public Merchant_t sharedByMerchant; // optional
  public Customer_t sharedByCustomer; // optional
  public int shareCount; // optional
  public long redeemed; // optional
  public long created; // optional
  public long updated; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DEAL_ACQUIRE_ID((short)1, "dealAcquireId"),
    DEAL((short)2, "deal"),
    STATUS((short)3, "status"),
    SHARED_BY_MERCHANT((short)4, "sharedByMerchant"),
    SHARED_BY_CUSTOMER((short)5, "sharedByCustomer"),
    SHARE_COUNT((short)6, "shareCount"),
    REDEEMED((short)7, "redeemed"),
    CREATED((short)8, "created"),
    UPDATED((short)9, "updated");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DEAL_ACQUIRE_ID
          return DEAL_ACQUIRE_ID;
        case 2: // DEAL
          return DEAL;
        case 3: // STATUS
          return STATUS;
        case 4: // SHARED_BY_MERCHANT
          return SHARED_BY_MERCHANT;
        case 5: // SHARED_BY_CUSTOMER
          return SHARED_BY_CUSTOMER;
        case 6: // SHARE_COUNT
          return SHARE_COUNT;
        case 7: // REDEEMED
          return REDEEMED;
        case 8: // CREATED
          return CREATED;
        case 9: // UPDATED
          return UPDATED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SHARECOUNT_ISSET_ID = 0;
  private static final int __REDEEMED_ISSET_ID = 1;
  private static final int __CREATED_ISSET_ID = 2;
  private static final int __UPDATED_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.DEAL_ACQUIRE_ID,_Fields.STATUS,_Fields.SHARED_BY_MERCHANT,_Fields.SHARED_BY_CUSTOMER,_Fields.SHARE_COUNT,_Fields.REDEEMED,_Fields.CREATED,_Fields.UPDATED};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DEAL_ACQUIRE_ID, new org.apache.thrift.meta_data.FieldMetaData("dealAcquireId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DEAL, new org.apache.thrift.meta_data.FieldMetaData("deal", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Deal_t.class)));
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SHARED_BY_MERCHANT, new org.apache.thrift.meta_data.FieldMetaData("sharedByMerchant", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Merchant_t.class)));
    tmpMap.put(_Fields.SHARED_BY_CUSTOMER, new org.apache.thrift.meta_data.FieldMetaData("sharedByCustomer", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Customer_t.class)));
    tmpMap.put(_Fields.SHARE_COUNT, new org.apache.thrift.meta_data.FieldMetaData("shareCount", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.REDEEMED, new org.apache.thrift.meta_data.FieldMetaData("redeemed", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "Timestamp")));
    tmpMap.put(_Fields.CREATED, new org.apache.thrift.meta_data.FieldMetaData("created", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "Timestamp")));
    tmpMap.put(_Fields.UPDATED, new org.apache.thrift.meta_data.FieldMetaData("updated", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "Timestamp")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DealAcquire_t.class, metaDataMap);
  }

  public DealAcquire_t() {
  }

  public DealAcquire_t(
    Deal_t deal)
  {
    this();
    this.deal = deal;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DealAcquire_t(DealAcquire_t other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetDealAcquireId()) {
      this.dealAcquireId = other.dealAcquireId;
    }
    if (other.isSetDeal()) {
      this.deal = new Deal_t(other.deal);
    }
    if (other.isSetStatus()) {
      this.status = other.status;
    }
    if (other.isSetSharedByMerchant()) {
      this.sharedByMerchant = new Merchant_t(other.sharedByMerchant);
    }
    if (other.isSetSharedByCustomer()) {
      this.sharedByCustomer = new Customer_t(other.sharedByCustomer);
    }
    this.shareCount = other.shareCount;
    this.redeemed = other.redeemed;
    this.created = other.created;
    this.updated = other.updated;
  }

  public DealAcquire_t deepCopy() {
    return new DealAcquire_t(this);
  }

  public void clear() {
    this.dealAcquireId = null;
    this.deal = null;
    this.status = null;
    this.sharedByMerchant = null;
    this.sharedByCustomer = null;
    setShareCountIsSet(false);
    this.shareCount = 0;
    setRedeemedIsSet(false);
    this.redeemed = 0;
    setCreatedIsSet(false);
    this.created = 0;
    setUpdatedIsSet(false);
    this.updated = 0;
  }

  public String getDealAcquireId() {
    return this.dealAcquireId;
  }

  public DealAcquire_t setDealAcquireId(String dealAcquireId) {
    this.dealAcquireId = dealAcquireId;
    return this;
  }

  public void unsetDealAcquireId() {
    this.dealAcquireId = null;
  }

  /** Returns true if field dealAcquireId is set (has been assigned a value) and false otherwise */
  public boolean isSetDealAcquireId() {
    return this.dealAcquireId != null;
  }

  public void setDealAcquireIdIsSet(boolean value) {
    if (!value) {
      this.dealAcquireId = null;
    }
  }

  public Deal_t getDeal() {
    return this.deal;
  }

  public DealAcquire_t setDeal(Deal_t deal) {
    this.deal = deal;
    return this;
  }

  public void unsetDeal() {
    this.deal = null;
  }

  /** Returns true if field deal is set (has been assigned a value) and false otherwise */
  public boolean isSetDeal() {
    return this.deal != null;
  }

  public void setDealIsSet(boolean value) {
    if (!value) {
      this.deal = null;
    }
  }

  public String getStatus() {
    return this.status;
  }

  public DealAcquire_t setStatus(String status) {
    this.status = status;
    return this;
  }

  public void unsetStatus() {
    this.status = null;
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return this.status != null;
  }

  public void setStatusIsSet(boolean value) {
    if (!value) {
      this.status = null;
    }
  }

  public Merchant_t getSharedByMerchant() {
    return this.sharedByMerchant;
  }

  public DealAcquire_t setSharedByMerchant(Merchant_t sharedByMerchant) {
    this.sharedByMerchant = sharedByMerchant;
    return this;
  }

  public void unsetSharedByMerchant() {
    this.sharedByMerchant = null;
  }

  /** Returns true if field sharedByMerchant is set (has been assigned a value) and false otherwise */
  public boolean isSetSharedByMerchant() {
    return this.sharedByMerchant != null;
  }

  public void setSharedByMerchantIsSet(boolean value) {
    if (!value) {
      this.sharedByMerchant = null;
    }
  }

  public Customer_t getSharedByCustomer() {
    return this.sharedByCustomer;
  }

  public DealAcquire_t setSharedByCustomer(Customer_t sharedByCustomer) {
    this.sharedByCustomer = sharedByCustomer;
    return this;
  }

  public void unsetSharedByCustomer() {
    this.sharedByCustomer = null;
  }

  /** Returns true if field sharedByCustomer is set (has been assigned a value) and false otherwise */
  public boolean isSetSharedByCustomer() {
    return this.sharedByCustomer != null;
  }

  public void setSharedByCustomerIsSet(boolean value) {
    if (!value) {
      this.sharedByCustomer = null;
    }
  }

  public int getShareCount() {
    return this.shareCount;
  }

  public DealAcquire_t setShareCount(int shareCount) {
    this.shareCount = shareCount;
    setShareCountIsSet(true);
    return this;
  }

  public void unsetShareCount() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SHARECOUNT_ISSET_ID);
  }

  /** Returns true if field shareCount is set (has been assigned a value) and false otherwise */
  public boolean isSetShareCount() {
    return EncodingUtils.testBit(__isset_bitfield, __SHARECOUNT_ISSET_ID);
  }

  public void setShareCountIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SHARECOUNT_ISSET_ID, value);
  }

  public long getRedeemed() {
    return this.redeemed;
  }

  public DealAcquire_t setRedeemed(long redeemed) {
    this.redeemed = redeemed;
    setRedeemedIsSet(true);
    return this;
  }

  public void unsetRedeemed() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __REDEEMED_ISSET_ID);
  }

  /** Returns true if field redeemed is set (has been assigned a value) and false otherwise */
  public boolean isSetRedeemed() {
    return EncodingUtils.testBit(__isset_bitfield, __REDEEMED_ISSET_ID);
  }

  public void setRedeemedIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __REDEEMED_ISSET_ID, value);
  }

  public long getCreated() {
    return this.created;
  }

  public DealAcquire_t setCreated(long created) {
    this.created = created;
    setCreatedIsSet(true);
    return this;
  }

  public void unsetCreated() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CREATED_ISSET_ID);
  }

  /** Returns true if field created is set (has been assigned a value) and false otherwise */
  public boolean isSetCreated() {
    return EncodingUtils.testBit(__isset_bitfield, __CREATED_ISSET_ID);
  }

  public void setCreatedIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CREATED_ISSET_ID, value);
  }

  public long getUpdated() {
    return this.updated;
  }

  public DealAcquire_t setUpdated(long updated) {
    this.updated = updated;
    setUpdatedIsSet(true);
    return this;
  }

  public void unsetUpdated() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __UPDATED_ISSET_ID);
  }

  /** Returns true if field updated is set (has been assigned a value) and false otherwise */
  public boolean isSetUpdated() {
    return EncodingUtils.testBit(__isset_bitfield, __UPDATED_ISSET_ID);
  }

  public void setUpdatedIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __UPDATED_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DEAL_ACQUIRE_ID:
      if (value == null) {
        unsetDealAcquireId();
      } else {
        setDealAcquireId((String)value);
      }
      break;

    case DEAL:
      if (value == null) {
        unsetDeal();
      } else {
        setDeal((Deal_t)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((String)value);
      }
      break;

    case SHARED_BY_MERCHANT:
      if (value == null) {
        unsetSharedByMerchant();
      } else {
        setSharedByMerchant((Merchant_t)value);
      }
      break;

    case SHARED_BY_CUSTOMER:
      if (value == null) {
        unsetSharedByCustomer();
      } else {
        setSharedByCustomer((Customer_t)value);
      }
      break;

    case SHARE_COUNT:
      if (value == null) {
        unsetShareCount();
      } else {
        setShareCount((Integer)value);
      }
      break;

    case REDEEMED:
      if (value == null) {
        unsetRedeemed();
      } else {
        setRedeemed((Long)value);
      }
      break;

    case CREATED:
      if (value == null) {
        unsetCreated();
      } else {
        setCreated((Long)value);
      }
      break;

    case UPDATED:
      if (value == null) {
        unsetUpdated();
      } else {
        setUpdated((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DEAL_ACQUIRE_ID:
      return getDealAcquireId();

    case DEAL:
      return getDeal();

    case STATUS:
      return getStatus();

    case SHARED_BY_MERCHANT:
      return getSharedByMerchant();

    case SHARED_BY_CUSTOMER:
      return getSharedByCustomer();

    case SHARE_COUNT:
      return Integer.valueOf(getShareCount());

    case REDEEMED:
      return Long.valueOf(getRedeemed());

    case CREATED:
      return Long.valueOf(getCreated());

    case UPDATED:
      return Long.valueOf(getUpdated());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DEAL_ACQUIRE_ID:
      return isSetDealAcquireId();
    case DEAL:
      return isSetDeal();
    case STATUS:
      return isSetStatus();
    case SHARED_BY_MERCHANT:
      return isSetSharedByMerchant();
    case SHARED_BY_CUSTOMER:
      return isSetSharedByCustomer();
    case SHARE_COUNT:
      return isSetShareCount();
    case REDEEMED:
      return isSetRedeemed();
    case CREATED:
      return isSetCreated();
    case UPDATED:
      return isSetUpdated();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DealAcquire_t)
      return this.equals((DealAcquire_t)that);
    return false;
  }

  public boolean equals(DealAcquire_t that) {
    if (that == null)
      return false;

    boolean this_present_dealAcquireId = true && this.isSetDealAcquireId();
    boolean that_present_dealAcquireId = true && that.isSetDealAcquireId();
    if (this_present_dealAcquireId || that_present_dealAcquireId) {
      if (!(this_present_dealAcquireId && that_present_dealAcquireId))
        return false;
      if (!this.dealAcquireId.equals(that.dealAcquireId))
        return false;
    }

    boolean this_present_deal = true && this.isSetDeal();
    boolean that_present_deal = true && that.isSetDeal();
    if (this_present_deal || that_present_deal) {
      if (!(this_present_deal && that_present_deal))
        return false;
      if (!this.deal.equals(that.deal))
        return false;
    }

    boolean this_present_status = true && this.isSetStatus();
    boolean that_present_status = true && that.isSetStatus();
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (!this.status.equals(that.status))
        return false;
    }

    boolean this_present_sharedByMerchant = true && this.isSetSharedByMerchant();
    boolean that_present_sharedByMerchant = true && that.isSetSharedByMerchant();
    if (this_present_sharedByMerchant || that_present_sharedByMerchant) {
      if (!(this_present_sharedByMerchant && that_present_sharedByMerchant))
        return false;
      if (!this.sharedByMerchant.equals(that.sharedByMerchant))
        return false;
    }

    boolean this_present_sharedByCustomer = true && this.isSetSharedByCustomer();
    boolean that_present_sharedByCustomer = true && that.isSetSharedByCustomer();
    if (this_present_sharedByCustomer || that_present_sharedByCustomer) {
      if (!(this_present_sharedByCustomer && that_present_sharedByCustomer))
        return false;
      if (!this.sharedByCustomer.equals(that.sharedByCustomer))
        return false;
    }

    boolean this_present_shareCount = true && this.isSetShareCount();
    boolean that_present_shareCount = true && that.isSetShareCount();
    if (this_present_shareCount || that_present_shareCount) {
      if (!(this_present_shareCount && that_present_shareCount))
        return false;
      if (this.shareCount != that.shareCount)
        return false;
    }

    boolean this_present_redeemed = true && this.isSetRedeemed();
    boolean that_present_redeemed = true && that.isSetRedeemed();
    if (this_present_redeemed || that_present_redeemed) {
      if (!(this_present_redeemed && that_present_redeemed))
        return false;
      if (this.redeemed != that.redeemed)
        return false;
    }

    boolean this_present_created = true && this.isSetCreated();
    boolean that_present_created = true && that.isSetCreated();
    if (this_present_created || that_present_created) {
      if (!(this_present_created && that_present_created))
        return false;
      if (this.created != that.created)
        return false;
    }

    boolean this_present_updated = true && this.isSetUpdated();
    boolean that_present_updated = true && that.isSetUpdated();
    if (this_present_updated || that_present_updated) {
      if (!(this_present_updated && that_present_updated))
        return false;
      if (this.updated != that.updated)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(DealAcquire_t other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    DealAcquire_t typedOther = (DealAcquire_t)other;

    lastComparison = Boolean.valueOf(isSetDealAcquireId()).compareTo(typedOther.isSetDealAcquireId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDealAcquireId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dealAcquireId, typedOther.dealAcquireId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDeal()).compareTo(typedOther.isSetDeal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDeal()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.deal, typedOther.deal);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStatus()).compareTo(typedOther.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, typedOther.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSharedByMerchant()).compareTo(typedOther.isSetSharedByMerchant());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSharedByMerchant()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sharedByMerchant, typedOther.sharedByMerchant);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSharedByCustomer()).compareTo(typedOther.isSetSharedByCustomer());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSharedByCustomer()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sharedByCustomer, typedOther.sharedByCustomer);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetShareCount()).compareTo(typedOther.isSetShareCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetShareCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.shareCount, typedOther.shareCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRedeemed()).compareTo(typedOther.isSetRedeemed());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRedeemed()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.redeemed, typedOther.redeemed);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCreated()).compareTo(typedOther.isSetCreated());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreated()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.created, typedOther.created);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUpdated()).compareTo(typedOther.isSetUpdated());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUpdated()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.updated, typedOther.updated);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DealAcquire_t(");
    boolean first = true;

    if (isSetDealAcquireId()) {
      sb.append("dealAcquireId:");
      if (this.dealAcquireId == null) {
        sb.append("null");
      } else {
        sb.append(this.dealAcquireId);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("deal:");
    if (this.deal == null) {
      sb.append("null");
    } else {
      sb.append(this.deal);
    }
    first = false;
    if (isSetStatus()) {
      if (!first) sb.append(", ");
      sb.append("status:");
      if (this.status == null) {
        sb.append("null");
      } else {
        sb.append(this.status);
      }
      first = false;
    }
    if (isSetSharedByMerchant()) {
      if (!first) sb.append(", ");
      sb.append("sharedByMerchant:");
      if (this.sharedByMerchant == null) {
        sb.append("null");
      } else {
        sb.append(this.sharedByMerchant);
      }
      first = false;
    }
    if (isSetSharedByCustomer()) {
      if (!first) sb.append(", ");
      sb.append("sharedByCustomer:");
      if (this.sharedByCustomer == null) {
        sb.append("null");
      } else {
        sb.append(this.sharedByCustomer);
      }
      first = false;
    }
    if (isSetShareCount()) {
      if (!first) sb.append(", ");
      sb.append("shareCount:");
      sb.append(this.shareCount);
      first = false;
    }
    if (isSetRedeemed()) {
      if (!first) sb.append(", ");
      sb.append("redeemed:");
      sb.append(this.redeemed);
      first = false;
    }
    if (isSetCreated()) {
      if (!first) sb.append(", ");
      sb.append("created:");
      sb.append(this.created);
      first = false;
    }
    if (isSetUpdated()) {
      if (!first) sb.append(", ");
      sb.append("updated:");
      sb.append(this.updated);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (deal == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'deal' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (deal != null) {
      deal.validate();
    }
    if (sharedByMerchant != null) {
      sharedByMerchant.validate();
    }
    if (sharedByCustomer != null) {
      sharedByCustomer.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te.getMessage());
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te.getMessage());
    }
  }

  private static class DealAcquire_tStandardSchemeFactory implements SchemeFactory {
    public DealAcquire_tStandardScheme getScheme() {
      return new DealAcquire_tStandardScheme();
    }
  }

  private static class DealAcquire_tStandardScheme extends StandardScheme<DealAcquire_t> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DealAcquire_t struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DEAL_ACQUIRE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.dealAcquireId = iprot.readString();
              struct.setDealAcquireIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DEAL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.deal = new Deal_t();
              struct.deal.read(iprot);
              struct.setDealIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.status = iprot.readString();
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SHARED_BY_MERCHANT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.sharedByMerchant = new Merchant_t();
              struct.sharedByMerchant.read(iprot);
              struct.setSharedByMerchantIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // SHARED_BY_CUSTOMER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.sharedByCustomer = new Customer_t();
              struct.sharedByCustomer.read(iprot);
              struct.setSharedByCustomerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // SHARE_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.shareCount = iprot.readI32();
              struct.setShareCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // REDEEMED
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.redeemed = iprot.readI64();
              struct.setRedeemedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // CREATED
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.created = iprot.readI64();
              struct.setCreatedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // UPDATED
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.updated = iprot.readI64();
              struct.setUpdatedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DealAcquire_t struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.dealAcquireId != null) {
        if (struct.isSetDealAcquireId()) {
          oprot.writeFieldBegin(DEAL_ACQUIRE_ID_FIELD_DESC);
          oprot.writeString(struct.dealAcquireId);
          oprot.writeFieldEnd();
        }
      }
      if (struct.deal != null) {
        oprot.writeFieldBegin(DEAL_FIELD_DESC);
        struct.deal.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.status != null) {
        if (struct.isSetStatus()) {
          oprot.writeFieldBegin(STATUS_FIELD_DESC);
          oprot.writeString(struct.status);
          oprot.writeFieldEnd();
        }
      }
      if (struct.sharedByMerchant != null) {
        if (struct.isSetSharedByMerchant()) {
          oprot.writeFieldBegin(SHARED_BY_MERCHANT_FIELD_DESC);
          struct.sharedByMerchant.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.sharedByCustomer != null) {
        if (struct.isSetSharedByCustomer()) {
          oprot.writeFieldBegin(SHARED_BY_CUSTOMER_FIELD_DESC);
          struct.sharedByCustomer.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetShareCount()) {
        oprot.writeFieldBegin(SHARE_COUNT_FIELD_DESC);
        oprot.writeI32(struct.shareCount);
        oprot.writeFieldEnd();
      }
      if (struct.isSetRedeemed()) {
        oprot.writeFieldBegin(REDEEMED_FIELD_DESC);
        oprot.writeI64(struct.redeemed);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCreated()) {
        oprot.writeFieldBegin(CREATED_FIELD_DESC);
        oprot.writeI64(struct.created);
        oprot.writeFieldEnd();
      }
      if (struct.isSetUpdated()) {
        oprot.writeFieldBegin(UPDATED_FIELD_DESC);
        oprot.writeI64(struct.updated);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DealAcquire_tTupleSchemeFactory implements SchemeFactory {
    public DealAcquire_tTupleScheme getScheme() {
      return new DealAcquire_tTupleScheme();
    }
  }

  private static class DealAcquire_tTupleScheme extends TupleScheme<DealAcquire_t> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DealAcquire_t struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.deal.write(oprot);
      BitSet optionals = new BitSet();
      if (struct.isSetDealAcquireId()) {
        optionals.set(0);
      }
      if (struct.isSetStatus()) {
        optionals.set(1);
      }
      if (struct.isSetSharedByMerchant()) {
        optionals.set(2);
      }
      if (struct.isSetSharedByCustomer()) {
        optionals.set(3);
      }
      if (struct.isSetShareCount()) {
        optionals.set(4);
      }
      if (struct.isSetRedeemed()) {
        optionals.set(5);
      }
      if (struct.isSetCreated()) {
        optionals.set(6);
      }
      if (struct.isSetUpdated()) {
        optionals.set(7);
      }
      oprot.writeBitSet(optionals, 8);
      if (struct.isSetDealAcquireId()) {
        oprot.writeString(struct.dealAcquireId);
      }
      if (struct.isSetStatus()) {
        oprot.writeString(struct.status);
      }
      if (struct.isSetSharedByMerchant()) {
        struct.sharedByMerchant.write(oprot);
      }
      if (struct.isSetSharedByCustomer()) {
        struct.sharedByCustomer.write(oprot);
      }
      if (struct.isSetShareCount()) {
        oprot.writeI32(struct.shareCount);
      }
      if (struct.isSetRedeemed()) {
        oprot.writeI64(struct.redeemed);
      }
      if (struct.isSetCreated()) {
        oprot.writeI64(struct.created);
      }
      if (struct.isSetUpdated()) {
        oprot.writeI64(struct.updated);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DealAcquire_t struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.deal = new Deal_t();
      struct.deal.read(iprot);
      struct.setDealIsSet(true);
      BitSet incoming = iprot.readBitSet(8);
      if (incoming.get(0)) {
        struct.dealAcquireId = iprot.readString();
        struct.setDealAcquireIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.status = iprot.readString();
        struct.setStatusIsSet(true);
      }
      if (incoming.get(2)) {
        struct.sharedByMerchant = new Merchant_t();
        struct.sharedByMerchant.read(iprot);
        struct.setSharedByMerchantIsSet(true);
      }
      if (incoming.get(3)) {
        struct.sharedByCustomer = new Customer_t();
        struct.sharedByCustomer.read(iprot);
        struct.setSharedByCustomerIsSet(true);
      }
      if (incoming.get(4)) {
        struct.shareCount = iprot.readI32();
        struct.setShareCountIsSet(true);
      }
      if (incoming.get(5)) {
        struct.redeemed = iprot.readI64();
        struct.setRedeemedIsSet(true);
      }
      if (incoming.get(6)) {
        struct.created = iprot.readI64();
        struct.setCreatedIsSet(true);
      }
      if (incoming.get(7)) {
        struct.updated = iprot.readI64();
        struct.setUpdatedIsSet(true);
      }
    }
  }

}

